export const moduleCategories = {
  "Employee Onboarding": "HR & Management",
  "Basic KYC Details": "HR & Management",
  "DRA Profile": "HR & Management",
  Attendance: "HR & Management",
  "Salary + commission details": "HR & Management",
  "Complement / document request": "HR & Management",
  "Resignation process": "HR & Management",
  "Change logs": "HR & Management",
  Interview: "Interview",
  "Pre-Recruitment Process": "Employee Management",
  "Recruitment Process": "Employee Management",
  "Exit Feedback": "Employee Management",
  "Performance Appraisal": "Employee Management",
  "Training And Development": "Employee Management",
  "Employee Relation": "Employee Management",
  "ISO and Statutory Compliance": "Employee Management",
};
